CREATE DATABASE CABARE;
USE DATABE;
CREATE TABLE GENERO(
	ID_GEN INT PRIMARY KEY,
	GENERO VARCHAR (10) UNIQUE NOT NULL);
CREATE TABLE TIPO_USUÁRIO (
	ID_TIPO INT PRIMARY KEY,
    TIPO VARCHAR UNIQUE);
CREATE TABLE PUTA(
	ID_PUTA INT PRIMARY KEY,
    NOME VARCHAR(40) UNIQUE NOT NULL,
    IST VARCHAR (40) NOT NULL,
    GENERO INT NOT NULL,
    TIPO INT NOT NULL,
    
    CONSTRAINT FK_GENERO
    FOREIGN KEY (GENERO)
    REFERENCES GENERO(ID_GEN),
    
    CONSTRAINT FK_TIPO
    FOREIGN KEY (TIPO)
    REFERENCES TIPO(ID_TIPO));
